[package]
name = "classer"
version = "0.1.0"
edition = "2024"

[dependencies]
crevice = "*"
ggez = "0.10.0-rc0"
good_lp = { version = "1.14.0", default-features = false, features = ["clarabel"] }
nalgebra = "0.34.1"
rand = "0.9.2"
strum = { version = "0.27.2", features = ["derive"] }
